export interface NostrEvent {
  id: string;
  pubkey: string;
  created_at: number;
  kind: number;
  tags: string[][];
  content: string;
  sig: string;
}

export interface DecodedIdentifier {
  type: 'npub' | 'nsec' | 'note' | 'nevent' | 'nprofile' | 'naddr';
  data: {
    pubkey?: string;
    id?: string;
    kind?: number;
    dTag?: string;
    relays?: string[];
    author?: string;
  };
  tlv?: Array<{
    type: number;
    typeName: string;
    length: number;
    value: string;
  }>;
}

export interface ParsedResult {
  type: 'event' | 'identifier';
  data: NostrEvent | DecodedIdentifier;
}

export interface ValidationResult {
  isValid: boolean;
  idMatch: boolean;
  sigValid: boolean;
  errors: string[];
}

export const KIND_NAMES: Record<number, string> = {
  0: 'Profile Metadata',
  1: 'Text Note',
  2: 'Recommend Relay',
  3: 'Follow List',
  4: 'Encrypted Direct Messages',
  5: 'Event Deletion',
  6: 'Reposts',
  7: 'Reaction',
  8: 'Badge Award',
  9: 'Chat Message',
  10: 'Group Chat Threaded Reply (deprecated)',
  11: 'Thread',
  12: 'Group Thread Reply (deprecated)',
  13: 'Seal',
  14: 'Direct Message',
  15: 'File Message',
  16: 'Generic Repost',
  17: 'Reaction to Website',
  20: 'Picture',
  21: 'Video Event',
  22: 'Short-form Portrait Video',
  30: 'Internal Reference',
  31: 'External Web Reference',
  32: 'Hardcopy Reference',
  33: 'Prompt Reference',
  40: 'Channel Creation',
  41: 'Channel Metadata',
  42: 'Channel Message',
  43: 'Channel Hide Message',
  44: 'Channel Mute User',
  818: 'Merge Requests',
  1018: 'Poll Response',
  1063: 'File Metadata',
  1311: 'Live Chat Message',
  1617: 'Patches',
  1621: 'Issues',
  1622: 'Replies',
  1971: 'Problem Tracker',
  1984: 'Reporting',
  1985: 'Label',
  9734: 'Zap Request',
  9735: 'Zap',
  10000: 'Mute List',
  10001: 'Pin List',
  10002: 'Relay List Metadata',
  10003: 'Bookmark List',
  10004: 'Communities List',
  10005: 'Public Chats List',
  10006: 'Blocked Relays List',
  10007: 'Search Relays List',
  10009: 'User Groups List',
  10015: 'Interests List',
  10030: 'User Emoji List',
  30000: 'Follow Sets',
  30001: 'Generic Lists',
  30023: 'Long-form Content',
  30024: 'Draft Long-form Content',
  30078: 'Application-specific Data',
  30315: 'User Status',
  30402: 'Classified Listing',
  30403: 'Draft Classified Listing',
  30818: 'Wiki Article',
  31922: 'Date-Based Calendar Event',
  31923: 'Time-Based Calendar Event',
  31924: 'Calendar',
  31925: 'Calendar Event RSVP',
  32123: 'Repository Announcement',
  34550: 'Community Definition',
  39000: 'Group Metadata',
  39001: 'Group Admins',
  39002: 'Group Members',
};

export const TAG_MEANINGS: Record<string, string> = {
  'e': 'Event reference',
  'p': 'Profile reference', 
  'a': 'Addressable event reference',
  'r': 'Reference (URL)',
  't': 'Hashtag',
  'g': 'Geohash',
  'd': 'Identifier',
  'nonce': 'Proof of work nonce',
  'subject': 'Subject',
  'client': 'Client name',
  'title': 'Title',
  'image': 'Image URL',
  'summary': 'Summary',
  'published_at': 'Published timestamp',
  'expires': 'Expiration timestamp',
  'amount': 'Amount (millisats)',
  'lnurl': 'Lightning URL',
  'relays': 'Relay URLs',
  'bolt11': 'Lightning invoice',
  'preimage': 'Lightning preimage',
  'description': 'Description',
  'title': 'Article title',
  'summary': 'Article summary',
  'published_at': 'Original publication timestamp',
  'image': 'Cover image URL',
  'lang': 'Content language (ISO 639-1)',
  'content-warning': 'Content warning',
  'location': 'Geographic location',
  'pay': 'Lightning payment address',
  'zap': 'Zap target',
  'imeta': 'Image metadata',
  'video': 'Video URL',
  'audio': 'Audio URL',
  'hashtags': 'Social hashtags',
  'alt': 'Alt text for media',
  'url': 'URL reference',
  'x': 'SHA256 hash',
  'size': 'File size in bytes',
  'dim': 'Image dimensions (WxH)',
  'magnet': 'Magnet link',
  'i': 'External identity',
  'k': 'Kind number',
  'relay': 'Relay URL',
  'web': 'Web URL',
  'clone': 'Git clone URL',
  'maintainers': 'Project maintainers',
  'earliest-unique-commit': 'Earliest unique commit',
  'status': 'Status indicator',
  'closed': 'Closed timestamp',
  'open': 'Open timestamp',
  'author': 'Author pubkey',
  'committer': 'Committer pubkey',
  'parent-commit': 'Parent commit hash',
  'commit': 'Commit hash',
  'name': 'Name identifier',
  'about': 'Description text',
  'picture': 'Picture URL',
  'banner': 'Banner image URL',
  'nip05': 'NIP-05 identifier',
  'lud06': 'Lightning address (LNURL)',
  'lud16': 'Lightning address',
  'website': 'Website URL',
  'display_name': 'Display name',
  'username': 'Username',
  'bot': 'Bot indicator',
  'created_at': 'Creation timestamp',
  'updated_at': 'Update timestamp',
  'expires_at': 'Expiration timestamp',
  'starts': 'Start time',
  'ends': 'End time',
  'start_date': 'Start date',
  'end_date': 'End date',
  'frequency': 'Recurrence frequency',
  'interval': 'Recurrence interval',
  'until': 'Recurrence end date',
  'by_day': 'Days of week',
  'by_month': 'Months',
  'by_set_pos': 'Position in set',
  'wday': 'Weekday',
  'yday': 'Year day',
  'week': 'Week number',
  'month': 'Month number',
  'year': 'Year number',
  'rsvp': 'RSVP status',
  'fb': 'Free/busy status',
  'categories': 'Event categories',
  'geo': 'Geographic coordinates',
  'class': 'Classification level',
  'priority': 'Priority level',
  'sequence': 'Sequence number',
  'uid': 'Unique identifier',
  'recurrence-id': 'Recurrence instance ID',
  'related-to': 'Related event ID',
  'attendee': 'Event attendee',
  'organizer': 'Event organizer',
  'contact': 'Contact information',
  'comment': 'Comment text',
  'attach': 'Attachment URL',
  'categories': 'Categories list',
  'resources': 'Required resources',
  'request-status': 'Request status',
  'method': 'Calendar method',
  'prodid': 'Product identifier',
  'version': 'Version number',
  'calscale': 'Calendar scale',
  'tz': 'Timezone',
  'tzid': 'Timezone ID',
  'tzname': 'Timezone name',
  'tzoffsetfrom': 'Timezone offset from',
  'tzoffsetto': 'Timezone offset to',
  'tzurl': 'Timezone URL',
  'dtstart': 'Start date/time',
  'dtend': 'End date/time',
  'duration': 'Duration',
  'rrule': 'Recurrence rule',
  'rdate': 'Recurrence dates',
  'exdate': 'Exception dates',
  'exrule': 'Exception rule',
};